export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_SORT_MOVIES_ASC = 'FETCH_SORT_MOVIES_ASC'
export const FETCH_SORT_MOVIES_DESC = 'FETCH_SORT_MOVIES_DESC'
export const FETCH_SORT_MOVIES_BY_RATING = 'FETCH_SORT_MOVIES_BY_RATING'

